//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Ventas.wsRecargas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ventatelcel.com/ws/nusoap", ConfigurationName="wsRecargas.ApplicationServicesPortType")]
    public interface ApplicationServicesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ventatelcel.com/ws/index.php/ObtenSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return1")]
        string ObtenSaldo(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ventatelcel.com/ws/index.php/ObtenSaldoPDV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return1")]
        string ObtenSaldoPDV(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ventatelcel.com/ws/index.php/Paquetes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string Paquetes(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ventatelcel.com/ws/index.php/RecargaEWS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string RecargaEWS(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.ventatelcel.com/ws/index.php/VerificaRecarga", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string VerificaRecarga(string cadena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApplicationServicesPortTypeChannel : Sistema.Ventas.wsRecargas.ApplicationServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServicesPortTypeClient : System.ServiceModel.ClientBase<Sistema.Ventas.wsRecargas.ApplicationServicesPortType>, Sistema.Ventas.wsRecargas.ApplicationServicesPortType {
        
        public ApplicationServicesPortTypeClient() {
        }
        
        public ApplicationServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenSaldo(string cadena) {
            return base.Channel.ObtenSaldo(cadena);
        }
        
        public string ObtenSaldoPDV(string cadena) {
            return base.Channel.ObtenSaldoPDV(cadena);
        }
        
        public string Paquetes(string cadena) {
            return base.Channel.Paquetes(cadena);
        }
        
        public string RecargaEWS(string cadena) {
            return base.Channel.RecargaEWS(cadena);
        }
        
        public string VerificaRecarga(string cadena) {
            return base.Channel.VerificaRecarga(cadena);
        }
    }
}
